/*******************************************************************************
 * Copyright (c) 1999-2010, Vodafone Group Services
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without 
 * modification, are permitted provided that the following conditions 
 * are met:
 * 
 *     * Redistributions of source code must retain the above copyright 
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above 
 *       copyright notice, this list of conditions and the following 
 *       disclaimer in the documentation and/or other materials provided 
 *       with the distribution.
 *     * Neither the name of Vodafone Group Services nor the names of its 
 *       contributors may be used to endorse or promote products derived 
 *       from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING 
 * IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY 
 * OF SUCH DAMAGE.
 ******************************************************************************/

package com.wayfinder.syntaxedit;

import java.util.List;
import java.util.Vector;

public class ProjSettings extends javax.swing.JFrame {
    
    protected static class SoundDirListModel extends javax.swing.AbstractListModel {
        protected Vector<String> strings;
        public SoundDirListModel(List<String>dirs) {
            strings = new Vector<String>(dirs);
        }
        public List<String> ExtractList() { return strings; }
        public int getSize() { return strings.size(); }
        public Object getElementAt(int i) { return strings.elementAt(i); }
        public void removeAt(int i) {
            strings.remove(i);
            fireIntervalRemoved(this, i, i);
        }
        public void add(String dir) {
            if (strings.contains(dir)) {
                // No duplicates allowed
                return;
            }
            strings.add(dir);
            fireIntervalAdded(this, strings.size()-1, strings.size()-1);
        }
        private static final long serialVersionUID = 42L;
    }
    protected SyntaxTree tree;
    protected SoundDirListModel soundDirs;
    
    /** Creates new form ProjSettings */
    public ProjSettings(SyntaxTree tree) {
        this.tree = tree;
        soundDirs = new SoundDirListModel(tree.getSoundDirList());
        initComponents();
        jLangList.setSelectedItem(tree.getLanguage());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jVoicePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSubVoiceName = new javax.swing.JTextField();
        jLangList = new javax.swing.JComboBox();
        jSubVoiceLabel = new javax.swing.JLabel();
        jVoiceName = new javax.swing.JTextField();
        VoiceLabel = new javax.swing.JLabel();
        jLangLabel = new javax.swing.JLabel();
        jSoundPanel = new javax.swing.JPanel();
        jSoundDirScrollPane = new javax.swing.JScrollPane();
        jSoundDirList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jRemoveSoundDirButton = new javax.swing.JButton();
        jAddSoundDirButton = new javax.swing.JButton();
        jSoundDirToAddField = new javax.swing.JTextField();
        jOKButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jVoicePanel.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Project settings");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipady = -4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 60, 0, 0);
        jVoicePanel.add(jLabel2, gridBagConstraints);

        jSubVoiceName.setText(tree.getSubVoiceName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1, 0, 0);
        jVoicePanel.add(jSubVoiceName, gridBagConstraints);

        jLangList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DE", "EN", "SW" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 1, 0, 0);
        jVoicePanel.add(jLangList, gridBagConstraints);

        jSubVoiceLabel.setText("Sub voice");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 14;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jVoicePanel.add(jSubVoiceLabel, gridBagConstraints);

        jVoiceName.setText(tree.getVoiceName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 1, 0, 0);
        jVoicePanel.add(jVoiceName, gridBagConstraints);

        VoiceLabel.setLabelFor(jVoiceName);
        VoiceLabel.setText("Voice name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 30, 0, 0);
        jVoicePanel.add(VoiceLabel, gridBagConstraints);

        jLangLabel.setLabelFor(jLangList);
        jLangLabel.setText("Language");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 0, 0);
        jVoicePanel.add(jLangLabel, gridBagConstraints);

        jTabbedPane1.addTab("Voice", jVoicePanel);

        jSoundPanel.setLayout(new java.awt.GridBagLayout());

        jSoundDirList.setModel(soundDirs);
        jSoundDirScrollPane.setViewportView(jSoundDirList);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jSoundPanel.add(jSoundDirScrollPane, gridBagConstraints);

        jLabel3.setText("Sound file search directories");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jSoundPanel.add(jLabel3, gridBagConstraints);

        jRemoveSoundDirButton.setText("Remove marked");
        jRemoveSoundDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveSoundDirButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jSoundPanel.add(jRemoveSoundDirButton, gridBagConstraints);

        jAddSoundDirButton.setText("Add new directory");
        jAddSoundDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddSoundDirButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jSoundPanel.add(jAddSoundDirButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jSoundPanel.add(jSoundDirToAddField, gridBagConstraints);

        jTabbedPane1.addTab("Sound files", jSoundPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jOKButton.setText("OK");
        jOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOKButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 50, 31, 0);
        getContentPane().add(jOKButton, gridBagConstraints);

        jCancelButton.setText("Cancel");
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 31, 31, 26);
        getContentPane().add(jCancelButton, gridBagConstraints);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents
    
    private void jAddSoundDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddSoundDirButtonActionPerformed
        String newDir = jSoundDirToAddField.getText();
        if (newDir != "") {
            soundDirs.add(newDir);
        }
        jSoundDirToAddField.setText("");
    }//GEN-LAST:event_jAddSoundDirButtonActionPerformed
    
    private void jRemoveSoundDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveSoundDirButtonActionPerformed
        int toRemove[] = jSoundDirList.getSelectedIndices();
        for (int a=toRemove.length-1; a>=0; --a) {
            soundDirs.removeAt(toRemove[a]);
        }
    }//GEN-LAST:event_jRemoveSoundDirButtonActionPerformed
    
    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jCancelButtonActionPerformed
    
    private void jOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOKButtonActionPerformed
        tree.setLanguage(jLangList.getSelectedItem().toString());
        tree.setVoiceName(jVoiceName.getText());
        tree.setSubVoiceName(jSubVoiceName.getText());
        tree.setSoundDirList(soundDirs.ExtractList());
        setVisible(false);
    }//GEN-LAST:event_jOKButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ProjSettings().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel VoiceLabel;
    public javax.swing.JButton jAddSoundDirButton;
    public javax.swing.JButton jCancelButton;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLangLabel;
    public javax.swing.JComboBox jLangList;
    public javax.swing.JButton jOKButton;
    public javax.swing.JButton jRemoveSoundDirButton;
    public javax.swing.JList jSoundDirList;
    public javax.swing.JScrollPane jSoundDirScrollPane;
    public javax.swing.JTextField jSoundDirToAddField;
    public javax.swing.JPanel jSoundPanel;
    public javax.swing.JLabel jSubVoiceLabel;
    public javax.swing.JTextField jSubVoiceName;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField jVoiceName;
    public javax.swing.JPanel jVoicePanel;
    // End of variables declaration//GEN-END:variables
    
    /** Shut up the compiler warnings
     */
    private static final long serialVersionUID = 42L;
}
